#/bin/sh
#-*-coding:utf-8 -*-
# 获取月初开始时间
firstDay="${1:-2018-11-01}"
# 计算月末截至时间
nextMonth=$(date -d "$firstDay 1 months" +"%Y-%m-%d %H:%M:%S")
# 格式化月初时间，将YYYY-mm-dd -> YYYY-mm-dd HH:MM:SS
firstDay=$(date -d "$firstDay" +"%Y-%m-%d %H:%M:%S")
echo "select sum(cpu_time), sum(memory_time), sum(disk_size_time), disk_type from (select id, cluster_id, cpu * live_time as cpu_time, memory * live_time as memory_time, disk_size * live_time as disk_size_time, disk_type, create_time, release_time, live_time from (select id, cluster_id, cpu, memory, disk_size, disk_type, create_time, release_time, TIMESTAMPDIFF(MINUTE, create_time, release_time) as live_time from (select n.id, n.cluster_id,  n.cpu as cpu, n.memory as memory, case when n.disk_type = 'ssd' then n.ephemeral else n.disk_size  end as disk_size, n.disk_type, case when i.created_at < '$firstDay' then '$firstDay' else i.created_at end as create_time, case when i.deleted_time >= '$nextMonth' or i.deleted_time is null then '$nextMonth' else i.deleted_time end as release_time from instances as i, node_groups as n where i.created_at < '$nextMonth' and (i.deleted_time is null or i.deleted_time >= '$firstDay') and i.node_group_id = n.id) as tmp_table) as up_level_table) as third_tmp_table group by disk_type;"
echo "select sum(cpu_time), sum(memory_time), sum(disk_size_time) from (select id, cluster_id, cpu * live_time as cpu_time, memory * live_time as memory_time, disk_size * live_time as disk_size_time, disk_type, create_time, release_time, live_time from (select id, cluster_id, cpu, memory, disk_size, disk_type, create_time, release_time, TIMESTAMPDIFF(MINUTE, create_time, release_time) as live_time from (select n.id, n.cluster_id,  n.cpu as cpu, n.memory as memory, case when n.disk_type = 'ssd' then n.ephemeral else n.disk_size  end as disk_size, n.disk_type, case when i.created_at < '$firstDay' then '$firstDay' else i.created_at end as create_time, case when i.deleted_time >= '$nextMonth' or i.deleted_time is null then '$nextMonth' else i.deleted_time end as release_time from instances as i, node_groups as n where i.created_at < '$nextMonth' and (i.deleted_time is null or i.deleted_time >= '$firstDay') and i.node_group_id = n.id) as tmp_table) as up_level_table) as third_tmp_table ;"
